"""
Shared constants for the backend application.
Centralizes magic numbers and configuration values for maintainability.
"""

# Rate Limiting Constants
DEFAULT_RATE_LIMIT_PER_MINUTE = 60
DEFAULT_RATE_LIMIT_PER_HOUR = 1000
DEFAULT_BURST_LIMIT = 10
PRODUCTION_RATE_LIMIT_PER_MINUTE = 120
PRODUCTION_RATE_LIMIT_PER_HOUR = 2000
PRODUCTION_BURST_LIMIT = 30

# Security Constants
BURST_WINDOW_SECONDS = 10
REQUEST_BODY_SCAN_LIMIT_BYTES = 10240  # 10KB
RATE_LIMIT_REDIS_KEY_TTL_SECONDS = 15
MINUTE_RATE_LIMIT_TTL_SECONDS = 70
HOUR_RATE_LIMIT_TTL_SECONDS = 3700

# Authentication Constants
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = 30
JWT_REFRESH_TOKEN_EXPIRE_DAYS = 7
PASSWORD_MIN_LENGTH = 8
TOTP_SECRET_LENGTH = 32
BACKUP_CODE_LENGTH = 8
EMAIL_VERIFICATION_TOKEN_EXPIRE_HOURS = 24

# Database Constants
MAX_RETRY_ATTEMPTS = 3
CONNECTION_POOL_SIZE = 10
CONNECTION_POOL_MAX_OVERFLOW = 20
QUERY_TIMEOUT_SECONDS = 30

# AI Service Constants
OPENAI_MAX_TOKENS = 4096
OPENAI_TEMPERATURE = 0.7
IMAGE_GENERATION_MAX_RETRIES = 3
CONTENT_GENERATION_TIMEOUT_SECONDS = 60
EMBEDDINGS_DIMENSION = 3072
SIMILARITY_THRESHOLD = 0.8

# Task Processing Constants
CELERY_TASK_TIMEOUT_SECONDS = 300  # 5 minutes
CELERY_MAX_RETRIES = 3
CELERY_RETRY_DELAY_SECONDS = 60
BATCH_SIZE_DEFAULT = 50
PAGINATION_DEFAULT_LIMIT = 20
PAGINATION_MAX_LIMIT = 100

# Cache Constants
DEFAULT_CACHE_TTL_SECONDS = 3600  # 1 hour
SHORT_CACHE_TTL_SECONDS = 300     # 5 minutes
LONG_CACHE_TTL_SECONDS = 86400    # 24 hours
REDIS_CONNECTION_TIMEOUT_SECONDS = 5

# File Upload Constants
MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024  # 10MB
ALLOWED_IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.gif', '.webp']
ALLOWED_DOCUMENT_EXTENSIONS = ['.pdf', '.doc', '.docx', '.txt']

# Social Media Platform Constants
TWITTER_CHAR_LIMIT = 280
INSTAGRAM_CAPTION_CHAR_LIMIT = 2200
FACEBOOK_POST_CHAR_LIMIT = 63206
LINKEDIN_POST_CHAR_LIMIT = 3000

# HTTP Status Codes (for consistency)
HTTP_SUCCESS = 200
HTTP_CREATED = 201
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_CONFLICT = 409
HTTP_RATE_LIMITED = 429
HTTP_INTERNAL_SERVER_ERROR = 500

# Logging Constants
LOG_MAX_LINE_LENGTH = 1000
LOG_RETENTION_DAYS = 30
DEBUG_LOG_MAX_ENTRIES = 1000

# WebSocket Constants
WS_PING_INTERVAL_SECONDS = 30
WS_PING_TIMEOUT_SECONDS = 10
WS_MAX_CONNECTIONS_PER_USER = 5

# Circuit Breaker Constants
CIRCUIT_BREAKER_FAILURE_THRESHOLD = 5
CIRCUIT_BREAKER_TIMEOUT_SECONDS = 60
CIRCUIT_BREAKER_RECOVERY_TIMEOUT_SECONDS = 30

# Performance Analysis Constants
DEFAULT_TOTAL_POSTS = 156
DEFAULT_AVG_ENGAGEMENT_RATE = 4.2
TOP_PERFORMING_REACH_THRESHOLD = 5000
LOW_PERFORMING_REACH_THRESHOLD = 500
OPTIMIZATION_MAX_TOKENS = 500
PERFORMANCE_REPORT_MAX_TOKENS = 400
AB_TEST_INSIGHTS_MAX_TOKENS = 400
DEFAULT_REPORT_DATE_RANGE_DAYS = 30

# Content Performance Constants
TWITTER_ENGAGEMENT_BOOST_MIN = 2.0
TWITTER_ENGAGEMENT_BOOST_MAX = 8.0
REACH_MIN_RANDOM = 500
REACH_MAX_RANDOM = 5000
CLICKS_MIN_RANDOM = 10
CLICKS_MAX_RANDOM = 200
MIN_AB_TEST_VARIANTS = 2

# Social Media Engagement Thresholds
HIGH_ENGAGEMENT_THRESHOLD = 6.0
MEDIUM_ENGAGEMENT_THRESHOLD = 4.0
LOW_ENGAGEMENT_THRESHOLD = 2.0

# Report Generation Constants
TOTAL_ENGAGEMENT_DEFAULT = 2847
TOTAL_REACH_DEFAULT = 45600
NEW_FOLLOWERS_DEFAULT = 342
CONTENT_PIECES_DEFAULT = 89

# Connection Health Constants
SECONDS_PER_HOUR = 3600
TOKEN_EXPIRY_SOON_HOURS = 72

# AI Suggestions / Personalization Constants
DEFAULT_SUGGESTION_LIMIT = 4
MAX_CONTENT_COUNT_DISPLAY = 999
DEFAULT_CREATIVITY_LEVEL = 0.7
DEFAULT_BRAND_VOICE = "professional"
DEFAULT_PLATFORMS = ("x", "instagram")