name: Safe Database Migration

on:
  workflow_call:
    inputs:
      environment:
        description: 'Target environment (staging/production)'
        required: true
        type: string
      target_revision:
        description: 'Target migration revision (default: head)'
        required: false
        type: string
        default: 'head'
      dry_run:
        description: 'Perform dry run without making changes'
        required: false
        type: boolean
        default: false
    secrets:
      DATABASE_URL:
        required: true
      POSTGRES_PASSWORD:
        required: true

jobs:
  safe-migration:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install safety psycopg2-binary
        
    - name: Install PostgreSQL client tools
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client
        
    - name: Verify database connection
      run: |
        echo "Testing database connection..."
        pg_isready -h localhost -p 5432 -U postgres
        
    - name: Setup test database schema
      if: inputs.environment == 'staging'
      run: |
        export PYTHONPATH=$PWD
        # Initialize Alembic if not already done
        if [ ! -f "alembic.ini" ]; then
          alembic init alembic
        fi
        
        # Create baseline migration if needed
        alembic upgrade head || echo "No migrations to apply"
      env:
        DATABASE_URL: postgresql://postgres:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/test_db
        
    - name: Pre-migration validation
      run: |
        echo "🔍 Running pre-migration validation..."
        
        # Check Alembic configuration
        python -c "
        import sys
        sys.path.append('.')
        try:
            from alembic.config import Config
            from alembic import command
            config = Config('alembic.ini')
            print('✅ Alembic configuration valid')
        except Exception as e:
            print(f'❌ Alembic configuration error: {e}')
            sys.exit(1)
        "
        
        # Validate database connectivity  
        python -c "
        import os
        import psycopg2
        try:
            conn = psycopg2.connect(os.getenv('DATABASE_URL'))
            conn.close()
            print('✅ Database connection successful')
        except Exception as e:
            print(f'❌ Database connection failed: {e}')
            sys.exit(1)
        "
        
        # Check for pending migrations
        export PYTHONPATH=$PWD
        python -c "
        from alembic.config import Config
        from alembic.runtime.migration import MigrationContext
        from alembic.script import ScriptDirectory
        import sys
        sys.path.append('.')
        
        try:
            config = Config('alembic.ini')
            script = ScriptDirectory.from_config(config)
            
            # This would normally connect to the actual database
            # For demo purposes, we'll just validate the script directory
            heads = script.get_heads()
            print(f'✅ Migration validation complete. Current heads: {heads}')
        except Exception as e:
            print(f'❌ Migration validation failed: {e}')
            sys.exit(1)
        "
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
    - name: Create migration backup directory
      run: |
        mkdir -p migration-backups
        echo "📁 Migration backup directory created"
        
    - name: Run safe migration (dry run)
      if: inputs.dry_run
      run: |
        echo "🔍 Running migration in DRY RUN mode..."
        python scripts/migration-guardrails.py \
          --database-url "$DATABASE_URL" \
          --target-revision "${{ inputs.target_revision }}" \
          --backup-dir migration-backups \
          --dry-run
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        PYTHONPATH: .
        
    - name: Run safe migration (production)
      if: ${{ !inputs.dry_run }}
      run: |
        echo "⚡ Running PRODUCTION migration with guardrails..."
        python scripts/migration-guardrails.py \
          --database-url "$DATABASE_URL" \
          --target-revision "${{ inputs.target_revision }}" \
          --backup-dir migration-backups
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        PYTHONPATH: .
        
    - name: Post-migration validation
      if: ${{ !inputs.dry_run }}
      run: |
        echo "✅ Running post-migration validation..."
        
        # Verify database is still accessible
        python -c "
        import os
        import psycopg2
        try:
            conn = psycopg2.connect(os.getenv('DATABASE_URL'))
            cursor = conn.cursor()
            cursor.execute('SELECT version();')
            result = cursor.fetchone()
            conn.close()
            print(f'✅ Database health check passed: {result[0][:50]}...')
        except Exception as e:
            print(f'❌ Database health check failed: {e}')
            sys.exit(1)
        "
        
        # Verify Alembic head is as expected
        export PYTHONPATH=$PWD
        python -c "
        import subprocess
        import sys
        import os
        
        try:
            result = subprocess.run(['alembic', 'current'], 
                                  capture_output=True, text=True, check=True,
                                  env={**os.environ, 'PYTHONPATH': '.'})
            print(f'✅ Post-migration Alembic head: {result.stdout.strip()}')
        except subprocess.CalledProcessError as e:
            print(f'❌ Failed to verify Alembic head: {e}')
            sys.exit(1)
        "
        
        echo "🎉 Post-migration validation completed successfully"
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
    - name: List available backups
      if: ${{ !inputs.dry_run }}
      run: |
        echo "📁 Migration backups created:"
        python scripts/migration-guardrails.py \
          --database-url "$DATABASE_URL" \
          --backup-dir migration-backups \
          --list-backups
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
    - name: Cleanup old backups
      if: inputs.environment == 'production'
      run: |
        echo "🧹 Cleaning up old migration backups (keeping 10 most recent)..."
        python scripts/migration-guardrails.py \
          --database-url "$DATABASE_URL" \
          --backup-dir migration-backups \
          --cleanup-backups 10
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
    - name: Upload migration artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: migration-artifacts-${{ inputs.environment }}-${{ github.run_number }}
        path: |
          migration-backups/
          *.log
        retention-days: 30
        
    - name: Migration failure notification
      if: failure()
      run: |
        echo "❌ MIGRATION FAILED - Check logs and backups"
        echo "🔄 Automatic rollback should have been attempted"
        echo "📁 Migration backups are available in artifacts"
        echo "🚨 Manual intervention may be required"
        
        # List available backups for recovery
        if [ -d "migration-backups" ]; then
          echo "📋 Available backups for manual recovery:"
          ls -la migration-backups/
        fi